// Public vehicle pages must never use `select("*")`. The vehicles table also
// stores owner-only identifiers and moderation fields, so public reads use this
// explicit allowlist. Keep it aligned with the safe columns returned by
// search_vehicles() in the latest database migration.
export const PUBLIC_VEHICLE_COLUMNS = [
  "id",
  "agency_id",
  "make",
  "model",
  "year",
  "color",
  "insurance_type",
  "fuel_policy",
  "daily_rate_lkr",
  "deposit_lkr",
  "seats",
  "transmission",
  "features",
  "status",
  "city",
  "slug",
  "photos",
  "created_at",
  "updated_at",
  "description",
  "monthly_rate_lkr",
  "vehicle_type",
  "self_drive",
  "with_driver",
  "airport_pickup",
  "daily_rate_usd",
  "mileage_limit",
  "extra_mileage_lkr",
  "rules",
  "badges",
  "is_featured",
  "fuel_type",
  "luggage",
  "body_type",
  "variant",
  "doors",
  "engine_cc",
  "odometer_km",
  "weekly_rate_lkr",
  "included_km_per_day",
  "unlimited_km",
  "refuel_fee_lkr",
  "cleaning_fee_lkr",
  "late_fee_per_hour_lkr",
  "delivery_available",
  "delivery_fee_lkr",
  "min_rental_days",
  "max_rental_days",
  "smoking_allowed",
  "pets_allowed",
  "ride_hail_allowed",
  "second_driver_allowed",
  "min_renter_age",
  "min_license_years",
  "restricted_use",
  "has_gps_tracker",
  "has_etc_tag",
  "per_km_rate_lkr",
  "tolls_included",
  "driver_bata_lkr",
  "verified_vehicle",
  "revenue_license_expiry",
  "insurance_expiry",
  "emission_expiry",
].join(", ");

export const PUBLIC_AGENCY_EMBED =
  "agencies(id, name, slug, city, provider_type, is_verified, reliability_pct, cancellation_count, avg_response_minutes, rating_avg, rating_count)";

export const PUBLIC_VEHICLE_WITH_AGENCY_SELECT =
  `${PUBLIC_VEHICLE_COLUMNS}, ${PUBLIC_AGENCY_EMBED}`;
